<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Ideas_Custom</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\ascendedodyssey.jpg" />
    <None Remove="Resources\AssetBundles\deathcatcher" />
    <None Remove="Resources\AssetBundles\hellnut" />
    <None Remove="Resources\AssetBundles\megadoomcabbage" />
    <None Remove="Resources\AssetBundles\pickeledpepper" />
    <None Remove="Resources\AssetBundles\shrinepot" />
    <None Remove="Resources\bladestar" />
    <None Remove="Resources\bowling" />
    <None Remove="Resources\bushplant" />
    <None Remove="Resources\clusterdoom" />
    <None Remove="Resources\dawning_shroom" />
    <None Remove="Resources\doomflower" />
    <None Remove="Resources\doomnutblover" />
    <None Remove="Resources\empaperzombie" />
    <None Remove="Resources\eventishroom" />
    <None Remove="Resources\explodonut" />
    <None Remove="Resources\fireclawzombie" />
    <None Remove="Resources\fireflower" />
    <None Remove="Resources\firepeashooter" />
    <None Remove="Resources\frenzerg" />
    <None Remove="Resources\frostumbrella" />
    <None Remove="Resources\fumeumbrella" />
    <None Remove="Resources\garlicboom" />
    <None Remove="Resources\garpuff" />
    <None Remove="Resources\goldengatling" />
    <None Remove="Resources\goldentycoongatling" />
    <None Remove="Resources\hybridmelon" />
    <None Remove="Resources\hypnopaperzombie" />
    <None Remove="Resources\icechomper" />
    <None Remove="Resources\icedoomultistar" />
    <None Remove="Resources\iceflower" />
    <None Remove="Resources\Images\Bullets\BuckportalBullet.png" />
    <None Remove="Resources\Images\Bullets\DarkHelmetBullet.png" />
    <None Remove="Resources\Images\Bullets\DoomCabbageBullet.png" />
    <None Remove="Resources\jalachomper" />
    <None Remove="Resources\jalahypno" />
    <None Remove="Resources\lasericeumbrella" />
    <None Remove="Resources\magmashroom" />
    <None Remove="Resources\marigoldbomb" />
    <None Remove="Resources\melonademortar" />
    <None Remove="Resources\obisidianchomper" />
    <None Remove="Resources\obsidianseed" />
    <None Remove="Resources\obsidian_peashooter" />
    <None Remove="Resources\pitchermystery" />
    <None Remove="Resources\protalhelmetgatling" />
    <None Remove="Resources\richsunflower" />
    <None Remove="Resources\saladgatling" />
    <None Remove="Resources\shrine" />
    <None Remove="Resources\silvergatling" />
    <None Remove="Resources\sniperfreeze" />
    <None Remove="Resources\sniperhypno" />
    <None Remove="Resources\stargloom" />
    <None Remove="Resources\stinkper" />
    <None Remove="Resources\summercabbage" />
    <None Remove="Resources\sunnycommando" />
    <None Remove="Resources\sunnygatling" />
    <None Remove="Resources\sunnysniper" />
    <None Remove="Resources\superfirecattail" />
    <None Remove="Resources\superfiregloom" />
    <None Remove="Resources\superfirestar" />
    <None Remove="Resources\supergatlingmine" />
    <None Remove="Resources\supericecattail" />
    <None Remove="Resources\twindoomnut" />
    <None Remove="Resources\twintycoonshooter" />
    <None Remove="Resources\ulthypnet" />
    <None Remove="Resources\ultimatejaladoomfume" />
    <None Remove="Resources\umbrellamine" />
    <None Remove="Resources\Images\bossrush.jpg" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\AssetBundles\bushplant" />
    <EmbeddedResource Include="Resources\AssetBundles\deathcatcher" />
    <EmbeddedResource Include="Resources\AssetBundles\hellnut" />
    <EmbeddedResource Include="Resources\AssetBundles\megadoomcabbage" />
    <EmbeddedResource Include="Resources\AssetBundles\pickeledpepper" />
    <EmbeddedResource Include="Resources\AssetBundles\saladgatling" />
    <EmbeddedResource Include="Resources\AssetBundles\shrinepot" />
    <EmbeddedResource Include="Resources\Images\ascendedodyssey.jpg" />
    <EmbeddedResource Include="Resources\AssetBundles\bladestar" />
    <EmbeddedResource Include="Resources\AssetBundles\bowling" />
    <EmbeddedResource Include="Resources\AssetBundles\clusterdoom" />
    <EmbeddedResource Include="Resources\AssetBundles\dawning_shroom" />
    <EmbeddedResource Include="Resources\AssetBundles\doomflower" />
    <EmbeddedResource Include="Resources\AssetBundles\doomnutblover" />
    <EmbeddedResource Include="Resources\AssetBundles\empaperzombie" />
    <EmbeddedResource Include="Resources\AssetBundles\eventishroom" />
    <EmbeddedResource Include="Resources\AssetBundles\explodonut" />
    <EmbeddedResource Include="Resources\AssetBundles\fireclawzombie" />
    <EmbeddedResource Include="Resources\AssetBundles\fireflower" />
    <EmbeddedResource Include="Resources\AssetBundles\firepeashooter" />
    <EmbeddedResource Include="Resources\AssetBundles\frenzerg" />
    <EmbeddedResource Include="Resources\AssetBundles\frostumbrella" />
    <EmbeddedResource Include="Resources\AssetBundles\fumeumbrella" />
    <EmbeddedResource Include="Resources\AssetBundles\garlicboom" />
    <EmbeddedResource Include="Resources\AssetBundles\garpuff" />
    <EmbeddedResource Include="Resources\AssetBundles\goldengatling" />
    <EmbeddedResource Include="Resources\AssetBundles\goldentycoongatling" />
    <EmbeddedResource Include="Resources\AssetBundles\hybridmelon" />
    <EmbeddedResource Include="Resources\AssetBundles\hypnopaperzombie" />
    <EmbeddedResource Include="Resources\AssetBundles\icechomper" />
    <EmbeddedResource Include="Resources\AssetBundles\icedoomultistar" />
    <EmbeddedResource Include="Resources\AssetBundles\iceflower" />
    <EmbeddedResource Include="Resources\AssetBundles\jalachomper" />
    <EmbeddedResource Include="Resources\AssetBundles\jalahypno" />
    <EmbeddedResource Include="Resources\AssetBundles\lasericeumbrella" />
    <EmbeddedResource Include="Resources\AssetBundles\magmashroom" />
    <EmbeddedResource Include="Resources\AssetBundles\marigoldbomb" />
    <EmbeddedResource Include="Resources\AssetBundles\melonademortar" />
    <EmbeddedResource Include="Resources\AssetBundles\obisidianchomper" />
    <EmbeddedResource Include="Resources\AssetBundles\obsidianseed" />
    <EmbeddedResource Include="Resources\AssetBundles\obsidian_peashooter" />
    <EmbeddedResource Include="Resources\AssetBundles\pitchermystery" />
    <EmbeddedResource Include="Resources\AssetBundles\protalhelmetgatling" />
    <EmbeddedResource Include="Resources\AssetBundles\richsunflower" />
    <EmbeddedResource Include="Resources\AssetBundles\shrine" />
    <EmbeddedResource Include="Resources\AssetBundles\silvergatling" />
    <EmbeddedResource Include="Resources\AssetBundles\sniperfreeze" />
    <EmbeddedResource Include="Resources\AssetBundles\sniperhypno" />
    <EmbeddedResource Include="Resources\AssetBundles\stargloom" />
    <EmbeddedResource Include="Resources\AssetBundles\stinkper" />
    <EmbeddedResource Include="Resources\AssetBundles\summercabbage" />
    <EmbeddedResource Include="Resources\AssetBundles\sunnycommando" />
    <EmbeddedResource Include="Resources\AssetBundles\sunnygatling" />
    <EmbeddedResource Include="Resources\AssetBundles\sunnysniper" />
    <EmbeddedResource Include="Resources\AssetBundles\superfirecattail" />
    <EmbeddedResource Include="Resources\AssetBundles\superfiregloom" />
    <EmbeddedResource Include="Resources\AssetBundles\superfirestar" />
    <EmbeddedResource Include="Resources\AssetBundles\supergatlingmine" />
    <EmbeddedResource Include="Resources\AssetBundles\supericecattail" />
    <EmbeddedResource Include="Resources\AssetBundles\twindoomnut" />
    <EmbeddedResource Include="Resources\AssetBundles\twintycoonshooter" />
    <EmbeddedResource Include="Resources\AssetBundles\ulthypnet" />
    <EmbeddedResource Include="Resources\AssetBundles\ultimatejaladoomfume" />
    <EmbeddedResource Include="Resources\AssetBundles\umbrellamine" />
    <EmbeddedResource Include="Resources\Images\bossrush.jpg" />
    <EmbeddedResource Include="Resources\Images\Bullets\BuckportalBullet.png" />
    <EmbeddedResource Include="Resources\Images\Bullets\DarkHelmetBullet.png" />
    <EmbeddedResource Include="Resources\Images\Bullets\DoomCabbageBullet.png" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\net6\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="CustomizeLib.MelonLoader">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\Mods\CustomizeLib.MelonLoader.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Common">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\net6\Il2CppInterop.Common.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSystem.Core">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\Il2CppSystem.Core.dll</HintPath>
    </Reference>
    <Reference Include="IndexRange">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\net6\IndexRange.dll</HintPath>
    </Reference>
    <Reference Include="MelonLoader">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\net6\MelonLoader.dll</HintPath>
    </Reference>
    <Reference Include="Unity.2D.Common.Runtime">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\Unity.2D.Common.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.2D.SpriteShape.Runtime">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\Unity.2D.SpriteShape.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.2D.Tilemap.Extras">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\Unity.2D.Tilemap.Extras.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="Unity.VisualScripting.Core">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\Unity.VisualScripting.Core.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VirtualTexturingModule">
      <HintPath>..\..\..\PvZ\PVZF 3.2.1 English Plus\MelonLoader\Il2CppAssemblies\UnityEngine.VirtualTexturingModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
